name: cicd

on:
  push:
    branches: [workflow]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  CICD:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@d6257a36a9854d7936ed3756ff29b890f217b85b

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: schmidli/runeql:${{ env.GITHUB_REF_SLUG }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Copy docker-compose.yml to server
        if: ${{ env.GITHUB_REF_SLUG  == 'master' }}
        uses: appleboy/scp-action@edc8ec9139a2687bcebf0249d0352ff2a988df00
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.yml"
          target: "/home/${{ secrets.SSH_USERNAME }}"

      - name: Pull and Deploy Image on server
        if: ${{ env.GITHUB_REF_SLUG  == 'master' }}
        uses: appleboy/ssh-action@61e292b601b405c4b211ea30a046bb1a97e45bdc
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker-compose pull
            docker-compose up -d

      - name: Rebuild Autodocs
        if: ${{ env.GITHUB_REF_SLUG  == 'master' }}
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
